"""Add language and category tables

Revision ID: 32c0044f6426
Revises: 723085b902db
Create Date: 2025-12-08 15:57:25.925198

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "32c0044f6426"
down_revision = "723085b902db"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "languages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("lists", schema=None) as batch_op:
        batch_op.add_column(sa.Column("language_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("category_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "languages", ["language_id"], ["id"])
        batch_op.create_foreign_key(None, "categories", ["category_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lists", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("category_id")
        batch_op.drop_column("language_id")

    op.drop_table("languages")
    op.drop_table("categories")
    # ### end Alembic commands ###
