"""Add entry_type field to Word model

Revision ID: 6f08792df825
Revises: f1876ddfc23d
Create Date: 2025-12-07 14:09:28.204850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f08792df825'
down_revision = 'f1876ddfc23d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_type', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_column('entry_type')

    # ### end Alembic commands ###
