"""Add quiz session status and resume capability

Revision ID: 723085b902db
Revises: 02523fe58610
Create Date: 2025-12-08 00:26:42.683161

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "723085b902db"
down_revision = "02523fe58610"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("quiz_sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("current_index", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("status", sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column("started_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("quiz_data", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("quiz_sessions", schema=None) as batch_op:
        batch_op.drop_column("quiz_data")
        batch_op.drop_column("started_at")
        batch_op.drop_column("status")
        batch_op.drop_column("current_index")

    # ### end Alembic commands ###
