"""Rename words table to entries

Revision ID: fdaed3f806f3
Revises: 6f08792df825
Create Date: 2025-12-07 14:31:31.568574

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fdaed3f806f3'
down_revision = '6f08792df825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('source_word', sa.String(length=200), nullable=False),
    sa.Column('target_word', sa.String(length=200), nullable=False),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('correct_count', sa.Integer(), nullable=True),
    sa.Column('incorrect_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['word_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('words')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('list_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_word', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('target_word', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('correct_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('incorrect_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('entry_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['word_lists.id'], name=op.f('words_list_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('words_pkey'))
    )
    op.drop_table('entries')
    # ### end Alembic commands ###
